[package]
name = "viva_streamer"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net"] }
tracing.workspace = true
viva-zenoh-api.workspace = true
zenoh.workspace = true
